### PR TITLE
[IOS] Fix for manual build step

### LINKED ISSUE #121: [IOS] Extra manual step for splash screens with xcode 7.1?
It seems we now need to press a "Use Launch Image Assets" button (or something like that) in the general tab in order to let splash screens work. @avdwerff could this be automated? Do you also have this issue?

### PR DESCRIPTION
**Pull request by tvervest**
Added placeholder launch image and changed default launch image catalog to be set to "LaunchImage" and fixes #121

### CODE REVIEW

**Comment by tvervest** [comment]
Didn't @avdwerff comment in slack that there was an additional change required to make this work?

**Comment by shawninder** [comment]
yeah, but then I tested it and it worked...

**Comment by tvervest** [comment]
Hmm, strange... well, if it works, who am I to complaint :stuck_out_tongue: Let's keep this in mind though, just in case any issues pop up, it's probably caused by this.

**Comment by avdwerff** [comment]
Ah, nice if it works :) ...I thought the npm xcode was causing it, apparently not. Cool.

**Pull request merged**
