### PR TITLE
Add permissions needed by plugins

### PR DESCRIPTION
**Pull request by shawninder**
This looks like it works. I'd just like to make sure there isn't something else to do that I don't know about. @michielibiza can you review this PR and confirm that this is enough?

### CODE REVIEW

**Comment by shawninder** [comment]
There is also a filter to add. Thomas know this, so I'm assigning him

**Comment by shawninder** [comment]
@tvervest Did you perhaps forget about this?

**Comment by tvervest** [comment]
@shawninder Indeed I did! But it's fixed now, have a test and merge if you're OK with the result :+1:

**Comment by shawninder** [comment]
@marcusbesjes Do you want to test and merge this? This is about making the that only the permissions needed are included in the android builds. So which permissions are included depends on which plugins you list as dependencies (and which plugins these plugins depend on as well of course). Each plugin is responsible for listing the permissions it needs, and this PR does the rest during the wrap phase.

**Pull request merged**
