### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by michielibiza**
The android builder and template now work for the Facebook test use case. I believe they are now feature complete and stable for the coming releases…
@marcusbesjes @shawninder Do any of you want to merge it in master and publish to npm?

### CODE REVIEW

**Comment by shawninder** [comment]
I can test and merge and publish this a little later today :)

**Comment by shawninder** [comment]
@michielibiza as you can see, Andre has merged this before I had time to test it. I think it's safer to make pull requests from other branches towards develop, not from develop towards master. For this time, I don't think we need to undo the merge, I'll just to the testing directly on master and comment here if anything seems wrong

**Comment by michielibiza** [comment]
@shawninder Ok, sure. So for releases we don't make PRs? Then what should we do: add tags? or send a mail with the hash of the commit?

**Comment by shawninder** [comment]
PRs are fine, just don't make them with the develop branch. Use feature branches. That way we can merge develop into master without unknowingly merging a PR

**Comment by michielibiza** [comment]
I'm trying to understand what you said. It looks like indeed you don't want to use PRs for merging develop into master...
What I tried to do earlier was signalling to you and marcus that develop was in a state that deserved to be published to npm. What is the desired way to do that?

**Comment by andrepadez** [comment]
i think, in a countinuous delivery environment, like we're trying to achieve there should be:
- pull request from feature to develop
- the reviewer, after testing (unit and quick functional) should merge into develop and push, wait for Travis ok
- someone else (the app owner) merges locally into master, runs tests again (unit and more extensive functional) push it and publish(if module)
- travis, sentinel and the packer-server will take care of the rest, if it's an app

I strongly emphasize the role of the project owner, which will be responsible to make sure if everything's ok. He can release several features/bugs at once, instead of being constantly releasing every single merge, depending on the complexity, mutability of the app and the amount of pull requests he has to deal with and also the urgency of each development

**Comment by andrepadez** [comment]
But for that we must also come up with a steady plan to manage the dependencies, and make sure everyone's on par with what is going on, any release to master should depend on a pure npm install to use it as intended

**Pull request merged**
